import { useState } from 'react';
const types = ['running', 'casual', 'formal', 'athletic', 'boots', 'sandals', 'sneakers'];
const colors = ['black', 'white', 'red', 'blue', 'brown', 'gray', 'green', 'pink', 'yellow'];
export default function FilterSidebar({ currentFilters: filters = {}, onFilterChange }) {
  const [open, setOpen] = useState(false);
  const update = (key, value) => onFilterChange({ ...filters, [key]: value });
  return <aside className="filter-sidebar"><button className="filter-toggle" aria-expanded={open} aria-controls="filter-controls" onClick={() => setOpen(!open)}>Refine your search <span aria-hidden="true">{open ? '−' : '+'}</span></button><div id="filter-controls" className={`filter-controls ${open ? 'is-open' : ''}`}><div className="filter-heading"><h2>Filters</h2><button className="text-link" onClick={() => onFilterChange({})}>Reset</button></div>
    <label className="filter-label">Style<select value={filters.type || ''} onChange={event => update('type', event.target.value)}><option value="">All styles</option>{types.map(type => <option key={type} value={type}>{type.charAt(0).toUpperCase() + type.slice(1)}</option>)}</select></label>
    <fieldset><legend>Color</legend><div className="color-options">{colors.map(color => <button key={color} className={filters.color === color ? 'selected' : ''} aria-pressed={filters.color === color} onClick={() => update('color', filters.color === color ? '' : color)}><span className="color-swatch" style={{ background: color }} aria-hidden="true" />{color}</button>)}</div></fieldset>
    <label className="filter-label">Size (US)<select value={filters.size || ''} onChange={event => update('size', event.target.value)}><option value="">All sizes</option>{Array.from({ length: 15 }, (_, i) => 6 + i / 2).map(size => <option key={size} value={size}>{size}</option>)}</select></label>
    <fieldset><legend>Budget</legend><div className="price-presets">{[50, 100, 150, 200].map(max => <button key={max} className={Number(filters.price_max) === max && Number(filters.price_min || 0) === 0 ? 'selected' : ''} onClick={() => onFilterChange({ ...filters, price_min: 0, price_max: max })}>Up to ${max}</button>)}</div><div className="price-inputs"><label>Min ($)<input type="number" min="0" step="0.01" value={filters.price_min ?? ''} placeholder="0" onChange={event => update('price_min', event.target.value)} /></label><label>Max ($)<input type="number" min="0" step="0.01" value={filters.price_max ?? ''} placeholder="Any" onChange={event => update('price_max', event.target.value)} /></label></div></fieldset>
  </div></aside>;
}
